pipeline {
    agent any

    environment {
        REPOSITORY_NAME = 'Backend'
        GITHUB_CREDENTIALS = credentials('Github-Credential')
        DOCKER_CREDENTIALS = credentials('Docker-Credential')
        IMAGE_NAME = 'wwh-test-service'
        DEMO_DIRECTORY = 'demo'
        DOCKER_REGISTRY_URL = "${DOCKER_CREDENTIALS_USR}/whh"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'CICD', url: "https://github.com/WooHyeopHa/${env.REPOSITORY_NAME}.git", credentialsId: 'Github-Credential'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir("${env.DEMO_DIRECTORY}") {
                        def image = docker.build("${env.IMAGE_NAME}:${env.BUILD_NUMBER}")
                        sh "docker login -u ${DOCKER_CREDENTIALS_USR} -p ${DOCKER_CREDENTIALS_PSW}"
                        sh "docker tag ${env.IMAGE_NAME}:${env.BUILD_NUMBER} ${env.DOCKER_REGISTRY_URL}:${env.BUILD_NUMBER}"
                        sh "docker push ${env.DOCKER_REGISTRY_URL}:${env.BUILD_NUMBER}"
                    }
                }
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    sh """
                    docker run -d -p 80:80 --name ${env.IMAGE_NAME} ${env.DOCKER_REGISTRY_URL}:${env.BUILD_NUMBER}
                    """
                }
            }
        }
    }

    post {
        success {
            echo '빌드 및 배포가 성공적으로 완료되었습니다!'
        }
        failure {
            echo '빌드 또는 배포에 실패했습니다.'
        }
    }
}
