server:
  port: 8080

spring:

  profiles:
    active: local, env

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}

apple:
  team-id: ${APPLE_TEAM_ID}
  login-key: ${APPLE_KEY_ID}
  client-id: ${APPLE_CLIENT_ID}
  redirect-url: ${APPLE_REDIRECT_URL}
  key-path: apple/AuthKey_${APPLE_KEY_ID}.p8
  auth-url: "https://appleid.apple.com"

jwt:
  secretKey: "${JWT_SECRET_KEY}"
  access:
    expiration: 3600
    header: "Authorization"
  refresh:
    expiration: 604800
    header: "X-Refresh-Token"

art:
  service-key: ${ART_SERVICE_KEY}
  musical: ${ART_MUSICAL}
  drama: ${ART_DRAMA}
  concert: ${ART_CONCERT}
  concert-magic: ${ART_CONCERT_MAGIC}
  dance: ${ART_DANCE}
  dance-basic: ${ART_DANCE_BASIC}
  classic: ${ART_CLASSIC}