server:
  port: 8080

spring:
  profiles:
    active: local, env

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}

