name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        user: ${{ secrets.JENKINS_USERNAME }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "wwh-exhibition-service"
